# Generated by Django 5.1.6 on 2025-03-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_seat_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='passenger',
        ),
        migrations.AddField(
            model_name='reservation',
            name='passenger_name',
            field=models.CharField(default='testuser', max_length=255),
            preserve_default=False,
        ),
    ]
